name: passou nos testes unitários?

# observa eventos na branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: clonar o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: configurar .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Passo 3: restaurar pacotes
      - name: Restore dependencies
        run: dotnet restore

      # Passo 4: build do projeto
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Passo 5: executar testes
      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal --configuration Release